CREATE TYPE "Testament" AS ENUM (
  'OldTestament',
  'NewTestament'
);

CREATE TYPE "Division" AS ENUM (
  'Pentateuch',
  'HistoricalBook',
  'WisdomBook',
  'MajorProphet',
  'MinorProphet',
  'Gospel',
  'History',
  'PaulineEpistle',
  'GeneralEpistle',
  'Prophecy'
);

CREATE TABLE "Language" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "Translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "language_id" integer UNIQUE NOT NULL,
  "name" varchar UNIQUE NOT NULL,
  "full_name" varchar UNIQUE,
  "year" varchar[4],
  "description" text
);

CREATE TABLE "Book" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "translation_id" integer UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "long_name" varchar NOT NULL,
  "regional_name" varchar,
  "regional_long_name" varchar,
  "book_number" integer NOT NULL,
  "abbreviation" varchar,
  "testament" Testament,
  "division" Division,
  "description" text
);

CREATE TABLE "Chapter" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_id" integer UNIQUE NOT NULL,
  "chapter_number" integer NOT NULL,
  "description" text
);

CREATE TABLE "Verse" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chapter_id" integer UNIQUE NOT NULL,
  "verse_number" integer,
  "verse" varchar NOT NULL
);

ALTER TABLE "Language" ADD FOREIGN KEY ("id") REFERENCES "Translation" ("language_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Translation" ADD FOREIGN KEY ("id") REFERENCES "Book" ("translation_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Book" ADD FOREIGN KEY ("id") REFERENCES "Chapter" ("book_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Chapter" ADD FOREIGN KEY ("id") REFERENCES "Verse" ("chapter_id") ON DELETE CASCADE ON UPDATE CASCADE;
